baseURL = 'https://dominicferrando.com/'
languageCode = 'en-us'
title = 'Dominic Ferrando'
theme = 'lekh'

[params]
Name = "Dominic Ferrando"
About = "Welcome! Here you will find a collection of stuff I find useful and interesting."
Email = "dominicf2001@gmail.com"
Resume = "resume-3.pdf" # Add the filename with file extension.
PostLimit = 4 # Sets the number of posts to display on the front page
GoatCounterCode = ""

[[params.profiles]]
name = "GitHub"
url = "https://github.com/dominicf2001"

# [[params.profiles]]
# name = "Twitter"
# url = "https://twitter.com/ba11b0y"

# [[params.profiles]]
# name = "Goodreads"
# url = "https://www.goodreads.com/user/show/91520565-rahul-tiwari"

# [[params.profiles]]
# name = "LinkedIn"
# url = ""
